# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Password_Generator.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIntValidator
import random
import string

class Ui_MainWindow(object):
    def AlertBox(self, Title, Message):
        Window = QtWidgets.QMessageBox()
        Window.setWindowTitle(Title)
        Window.setText(Message)
        Window.setStandardButtons(QtWidgets.QMessageBox.Ok)
        Window.exec_()

    def Generate_Random_Password(self):
        if self.Password_Limit.text() == "":
            self.AlertBox("Blank Message", "Please enter your password limit")
        else:
            Num = int(self.Password_Limit.text())
            pwd = ""
            for n in range(Num):
                Limit = random.randint(1, 90)
                pwd = pwd + string.printable[Limit]
        self.Password_Limit.clear()
        return self.Output_Box.setText(pwd)
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)
        MainWindow.setStyleSheet("background-color:pink")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.AppTitle = QtWidgets.QLabel(self.centralwidget)
        self.AppTitle.setGeometry(QtCore.QRect(70, 10, 501, 61))
        self.AppTitle.setStyleSheet("font-family:Arial;\n"
"font-weight:Bold;\n"
"font-size:28px;\n"
"color:white\n"
"")
        self.AppTitle.setObjectName("AppTitle")
        self.Password_Limit_Title = QtWidgets.QLabel(self.centralwidget)
        self.Password_Limit_Title.setGeometry(QtCore.QRect(70, 90, 501, 61))
        self.Password_Limit_Title.setStyleSheet("font-family:Arial;\n"
"font-weight:Bold;\n"
"font-size:20px;\n"
"color:white\n"
"")
        self.Password_Limit_Title.setObjectName("Password_Limit_Title")
        self.Password_Limit = QtWidgets.QLineEdit(self.centralwidget)
        self.Password_Limit.setGeometry(QtCore.QRect(70, 170, 501, 31))
        self.Password_Limit.setStyleSheet("font-family:Arial;\n"
"font-weight:bold;\n"
"padding:8px;\n"
"font-size:18px;\n"
"color:white;\n"
"border:2px solid white;\n"
"border-radius:8px")
        self.Password_Limit.setObjectName("Password_Limit")
        self.Password_Limit.setValidator(QIntValidator(1,99))
        self.Generate_Password_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Generate_Password_Button.clicked.connect(self.Generate_Random_Password)
        self.Generate_Password_Button.setGeometry(QtCore.QRect(70, 220, 511, 40))
        self.Generate_Password_Button.setStyleSheet("background-color: orange;\n"
"color:white;\n"
"font-family:arial;\n"
"font-weight:bold;\n"
"font-size:20px;\n"
"border:8px")
        self.Generate_Password_Button.setObjectName("Generate_Password_Button")
        self.Output_Box = QtWidgets.QLineEdit(self.centralwidget)
        self.Output_Box.setGeometry(QtCore.QRect(70, 270, 501, 31))
        self.Output_Box.setStyleSheet("font-family:arial;\n"
"font-weight:bold;\n"
"padding:8px;\n"
"font-size:18px;\n"
"color:white;\n"
"border:2px solid white;\n"
"border-radius:8px")
        self.Output_Box.setObjectName("Output_Box")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Strong Random Password Generator"))
        self.AppTitle.setText(_translate("MainWindow", "Strong Random Password Generator"))
        self.Password_Limit_Title.setText(_translate("MainWindow", "Enter your password limit"))
        self.Generate_Password_Button.setText(_translate("MainWindow", "Generate Password"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
